apiVersion: v1
kind: Service
metadata:
  name: svc-pod-2
spec:
  type: ClusterIP
  selector:
    app: segundo-pod
  ports: 
    - port: 9000 #Se colocar 80 aqui, e nao botar targetPort, ele vai escutar e enviar na mesma porta.
      targetPort: 80